### PR TITLE
Map of benin where a crop will succeed

### PR DESCRIPTION
**Pull request by akouete-kpakpo**
Following #37

### CODE REVIEW

**Comment by akouete-kpakpo** [comment]
@Ethel2003 @chrichri17 could you test this notebook and give your feedback as soon as possible?

Deadline tomorrow end of day.

**Comment by Ethel2003** [comment]
I tested the notebook and it's perfect!!!!!

**Comment by Ethel2003** [comment]
i had due to download the file of locations of communes. I ask me if the file wouldn't have to already in the notebook when i cloned the branch in local

**Review by Ethel2003 — APPROVED** [review]

**Comment by akouete-kpakpo** [comment]
> i had due to download the file of locations of communes. I ask me if the file wouldn't have to already in the notebook when i cloned the branch in local

Hi @Ethel2003 , the shapefile of the administrative boundaries of counties in Benin has to be downloaded. We can't put it in the notebook. Remember that git purpose is to version code, not data.

Obviously I can make a function to download it automatically so that the notebook runs in a standalone way but I'm not sure to have the time to do it before tomorrow. I agree it would be more user friendly though.

**Pull request merged**
