### PR TITLE
Test cartographie

### PR DESCRIPTION
**Pull request by Ethel2003**
I did the notebook about the cartography project. I just have  implemented the model of simulator and I run then for certains towns of Benin. It rest only how to generate map of Benin with the point that show what town is adequate for rice culture.

See and give me your view

### CODE REVIEW

**Comment by akouete-kpakpo** [comment]
@Ethel2003 good job! I'm very happy of the work done. I'll look as soon as possible and let you know.

**Comment by akouete-kpakpo** [comment]
please 
- remove notebook/02-refactor-leaf-area-index copy.ipynb
- remove images notebook/courbe_avant_irrigation.png, notebook/courbe_after_irrigation.png

**Comment by Ethel2003** [comment]
@akouete-kpakpo  I did it before the push but I don't know why it's here. I deleted the files and I stashed them. What solution you can give me??

**Comment by akouete-kpakpo** [comment]
you should not have stashed your changes. But rather commit them.

**Comment by akouete-kpakpo** [comment]
I amended your notebook to plot the growth metric on the map of Benin.

I think the simplest way to push my changes is to open another MR.

**Comment by akouete-kpakpo** [comment]
image

**Pull request closed without merging**
